### PR TITLE
Updated format for fraction output

### PR DESCRIPTION
**Pull request by HardikGoyal2003**
## Overview

1. This PR fixes or fixes part of  [#17219](https://github.com/oppia/oppia/issues/17219).
2. This PR does the following: Updates the output for fractions in Guppy.

## Proof that changes are correct

Build on local is working correctly.

https://github.com/oppia/guppy/assets/135348086/4415444a-520e-4e6c-80ef-c37632ed3664

### CODE REVIEW

**Comment by HardikGoyal2003** [comment]
@seanlip PTAL!

**Comment by seanlip** [comment]
@HardikGoyal2003 Look at past merged PRs -- don't you need to update the min.js file as well? https://github.com/oppia/guppy/pulls?q=is%3Apr+is%3Aclosed

**Comment by HardikGoyal2003** [comment]
@seanlip PTAL! Updated. Thanks!

**Comment by seanlip** [comment]
The minified file doesn't seem minified, and the changes there don't seem to follow the pattern in previous PRs. How did you do the minification? There should be instructions in the main repo explaining how to do this with an automatic command and I want to ensure we are following those.

**Comment by HardikGoyal2003** [comment]
@seanlip PTAL! Thanks!!

**Comment by seanlip** [comment]
@HardikGoyal2003 You haven't answered my question; how did you generate the min.js file?

**Comment by HardikGoyal2003** [comment]
@seanlip I just minify the guppy.js file, before changes was also correct, what was wrong in that file was I formatted that file. Otherwise change is similar.

**Comment by seanlip** [comment]
@HardikGoyal2003 Yes, what command did you use to do that, and which instructions did you follow? As a reviewer I need to understand how you generated it.

**Comment by HardikGoyal2003** [comment]
@seanlip To minify a file there are many online tools that minify the original js file, you just need to provide the original script. I checked for instructions also but nothing was mentioned about min.js file, then I tried to create the current min.js file using this tool, it was the same.

**Comment by HardikGoyal2003** [comment]
@seanlip [Tool](https://codebeautify.org/minify-js), if you will paste the guppy.js in this tool it will return you the min.js of that file.

**Review by seanlip — APPROVED** [review]
OK, this seems fine -- thanks @HardikGoyal2003 !

**Comment by HardikGoyal2003** [comment]
@seanlip Can this PR anyhow produce errors if versions are not updated on localhost?

**Update** 

min.js file changes are breaking the code and as it was occurring issues with this branch that's why I need to create a new branch for correction instead of using this branch.

**Comment by seanlip** [comment]
@HardikGoyal2003 Could you please explain a bit clearer what you're seeing?

- How do you know that min.js file changes are breaking the code?
- What is the line of code in Oppia that imports guppy -- can you point to it so that I can see how that is being handled?


Thanks.

**Comment by seanlip** [comment]
Ah -- I see the issue, min.js has too many changes.

I'm reverting this PR but not merging the new one. For the new one I would like to see end-to-end proof that it works before merging it. Please also answer the questions above still, thanks.

**Comment by HardikGoyal2003** [comment]
@seanlip Yeah now it's showing no error, after reverting the PR, otherwise, the console was full of errors and I knew that min.js file was breaking the code because of two reasons: as other files changed were not subjected to any error, and another thing is console showed that error has produced first in min.js file.

Then I analyzed and got to know the tool that was used to minify destroyed the min.js file as its efficiency was very low.

**Solution**
I used the same min.js file which was before my changes and just removed the code part, didn't change any formatting.
Now it won't cause any error.

**Import changes that I found was,** 
[Screencast from 21-02-24 12:19:30 AM IST.webm](https://github.com/oppia/guppy/assets/135348086/2c0bcbdc-80c7-4d7f-a359-6007293f7bba)

Now I will be changing these file again as commit hash will be changed.

Mention: I also found reference in yarn.lock but didn't touched that because it was already written in that file not to edit this file directly, is there any other file which need to be or not need be changed?



Thanks!

**Comment by seanlip** [comment]
Good analysis. I'm a bit worried that we don't have a specific way to minify here. Can you check https://guppy.js.org/site/contribute/ -- look at the "Build" command, maybe that helps?

Do not edit yarn.lock, but you do need to edit package.json. (I think the other one is just a dummy data file for tests.)

**Pull request merged**
